### ISSUE TITLE
SRI hash values in CSP do not match integrity attribute value added to script/style tags

### ISSUE THREAD

**Issue by dtrenz** [melloware/csp-webpack-plugin#136]
Hello. I'm attempting to use this plugin via `react-app-rewired` & `customize-cra` to be able to use CSP + SRI in my React app. However, then the app is built, the hashes added to `script-src` and `style-src` do not match the hashes in the `integrity` attributes of the injected script or style tags.

Any ideas why these hashes wouldn't match? Thanks

```js

const { override } = require("customize-cra");
const CspHtmlWebpackPlugin = require("@melloware/csp-webpack-plugin");

const cspConfigPolicy = {
  "script-src": "",
  "style-src": "",
};

const cspConfigOptions = {
  integrityEnabled: true,
  nonceEnabled: {
    "script-src": false,
    "style-src": false,
  },
  primeReactEnabled: false,
};

function addCspHtmlWebpackPlugin(config) {
  if (process.env.NODE_ENV === "production") {
    config.plugins.push(new CspHtmlWebpackPlugin(cspConfigPolicy, cspConfigOptions));
    config.output.crossOriginLoading = "anonymous";
  }
  return config;
}

module.exports = {
  webpack: override(addCspHtmlWebpackPlugin),
};
```

**Comment by melloware** [comment]
I am using this in production and it works.  A couple of things to make sure of....

1) your code built is being served I have seen this issue where the code was built in a docker container on the fly so if you were served by a load balancer the HASH was wrong depending on which server you hit.  So we build the code outside of docker container and then instsalled it so all servers were serving the EXACT same copy of the code.

2) your code isn't dynamically adding anything to the JS code after this step?

3) is this happening locally like you do an `npm run build` and then serve your app and the hash is wrong?

**Comment by melloware** [comment]
I have this sample project using it you can try?

https://github.com/melloware/react-security-hardening

Or compare yours to mine?

**Comment by dtrenz** [comment]
> is this happening locally like you do an npm run build and then serve your app and the hash is wrong?
Yes! This is happening locally when I run `npm run build` and serve on localhost. Is there a gotcha when running locally?

**Comment by dtrenz** [comment]
OK, I just verified that the sha384 hash in the `integrity` attribute is correct, but the sha384 hashes added to the CSP header are incorrect. Any idea how those could be different?

**Comment by dtrenz** [comment]
Looking through the code, it looks like hashes are created for inline script (`script:not([src])`) and style (`style:not([href])`) tags, and those hashes are added to the policy (probably the 3 hashes I'm seeing that I didn't recognize), but those hashes aren't added to the inline script/style tag's `integrity` attribute? I must be missing something, is that intentional?

**Comment by melloware** [comment]
I didn't write the original plugin but I added the SRI stuff.  I only use scripts which is probably why I didn't see this if the inline scripts are missing the values.

We might have to look at the SRI plugin capability but I thought it was only for script includes not inline scripts?

**Comment by dtrenz** [comment]
> We might have to look at the SRI plugin capability but I thought it was only for script includes not inline scripts?

I think you are correct. SRI is only relevant for script tags that have a `src`. That was my mistake.

OK, so I think my expectation was just incorrect. I expected the integrity hash that is added to the injected bundle script & style tags to also be added to the CSP policy meta tag, but it seems like those are separate concerns. I am now able to get the `main.*.js` bundle working by simply adding `'self'` to `script-src` and ignoring the `integrity` hash, as that is only used by the browser to do SRI checksum verification?

Does this sound right to you?

**Comment by melloware** [comment]
Yep!!

**Comment by melloware** [comment]
Did you get all your issues resolved is this safe to close?

**Comment by dtrenz** [comment]
Yes, all set. Thank you
